FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# GetEmployeeDetails

This API fetches employee details from database

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [

            {
                "DOT_EMPLOYEE": [
                    {
                        "EMPNO" : "1234",
                        "ENAME" : "RAJ",
                        "JOB" : "MANAGER",
                        "DEPTNO" : "20"
                    }, {
                        "EMPNO" : "45",
                        "ENAME" : "SAM",
                        "JOB" : "CLERK",
                        "DEPTNO" : "20"
                    }
                ]
            }
        ]